name: CI
on: push
jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Install dependencies
        run: yarn

      # TODO Uncomment when some tests are ready
      # - name: Test
      #   run: yarn test
